# Question 1:

In [12]:
import numpy as np

In [13]:
def gen_vander_matrix(inputVector, n, increasing=False):
    
    if not increasing:
        op_matx = np.array([x**(n-1-i) for x in inputVector for i in range(n)]).reshape(inputVector.size,n)
    elif increasing:
        op_matx = np.array([x**i for x in inputVector for i in range(n)]).reshape(inputVector.size,n)
    
    return op_matx

In [14]:
inputvector = np.array([1,2,3,4,5])
N = 5
dec_order = gen_vander_matrix(inputvector,N,False)
inc_order = gen_vander_matrix(inputvector,N,True)

In [15]:
dec_order

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [16]:
inc_order

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

In [17]:
# SECOND APPROACH
arr = np.array([1,2,3,4,5])
N=5

vander = np.vander(arr,N,increasing=False)

In [18]:
vander

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

# Question 2:

In [19]:
import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
a = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(a, n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
